# Generated by Django 5.0.6 on 2024-05-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('images', models.ImageField(upload_to='project_images/')),
            ],
        ),
    ]
